apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testingcatalog
  description: Developer Portal
  annotations:
    grafana/alert-label-selector: "service=awesome-service"
    grafana/dashboard-selector: "000000012"
    grafana/overview-dashboard: "https://play.grafana.org/d/000000012/grafana-play-home?orgId=1""
spec:
  type: website
  owner: user:default/santosh5321
  lifecycle: production
