apiVersion: backstage.io/v1alpha1
kind: MCP
metadata:
  name: my-mcp-santosh
  description: Example MCP SQL Service
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: mcp-service
  owner: santosh
  system: my-system
  mcpEndpoint: https://mcp.example.com/execute_sql
  # Add any other fields needed for your MCP service
