apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testingcatalog
  description: Developer Portal
  annotations:
    backstage.io/techdocs-ref: dir:.
    grafana/dashboard-selector: 'beh3fv2knta80a'
spec:
  type: website
  owner: user:default/santosh5321
  lifecycle: production
