apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: grafana-testing-entity
  annotations:
    grafana/dashboard-selector: "KGkUnV-Vz"
    grafana/overview-dashboard: "https://devopsanalytics-np.int.bayer.com/grafana/d/KGkUnV-Vz/dora-validation?orgId=1"
spec:
  type: website
  owner: santosh
  lifecycle: production
