apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testingcatalog
  description: Developer Portal
  annotations:
    grafana/alert-label-selector: "service=awesome-service"
    grafana/dashboard-selector: "beh3fv2knta80a"
    grafana/overview-dashboard: "https://devopsanalytics-np.int.bayer.com/grafana/d/beh3fv2knta80a/dora?orgId=1"
spec:
  type: website
  owner: user:default/santosh5321
  lifecycle: production
