apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: add-mcp-to-repo
  title: Add MCP Server to Repository
  description: Add Model Context Protocol (MCP) server implementation from bayer-int/mcp-servers to an existing repository
  tags:
    - mcp
    - model-context-protocol
    - integration
    - ml-service
spec:
  owner: default
  type: service
  
  parameters:
    - title: Repository Information
      required:
        - repoUrl
        - mcpType
      properties:
        repoUrl:
          title: Target Repository URL
          type: string
          description: The repository where MCP server will be added
          ui:field: RepoUrlPicker
          ui:options:
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
            allowedHosts:
              - github.com
        targetPath:
          title: Target Directory
          type: string
          description: Directory where MCP server code will be added
          default: 'mcp-server'
          ui:help: 'Subdirectory to create for MCP server (e.g., "mcp-server", "src/mcp")'
        mcpType:
          title: MCP Server Type
          type: string
          description: Select the type of MCP server to implement
          default: postgres
          enum:
            - postgres
            - filesystem
            - memory
            - sqlite
            - git
            - slack
            - github
            - brave-search
            - fetch
          enumNames:
            - PostgreSQL MCP Server
            - Filesystem MCP Server
            - Memory MCP Server
            - SQLite MCP Server
            - Git MCP Server
            - Slack MCP Server
            - GitHub MCP Server
            - Brave Search MCP Server
            - Fetch MCP Server

    - title: MCP Configuration
      required:
        - serviceName
        - owner
      properties:
        serviceName:
          title: Service Name
          type: string
          description: Name for the MCP service
          pattern: '^[a-z0-9-]+$'
          ui:help: 'Must be lowercase, alphanumeric, with hyphens only'
        owner:
          title: Owner
          type: string
          description: Owner of the MCP server
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
              - User
        
    - title: Database Configuration (for database-backed MCP types)
      dependencies:
        mcpType:
          oneOf:
            - properties:
                mcpType:
                  enum: ["postgres", "sqlite"]
      properties:
        databaseUrl:
          title: Database URL
          type: string
          description: Database connection URL (optional - can be configured via environment variables)
          ui:placeholder: 'postgresql://user:password@localhost:5432/dbname'
          ui:help: 'Leave empty to use environment variable DATABASE_URL'
        tableName:
          title: Table Name
          type: string
          description: Primary table name for MCP operations
          default: 'mcp_data'

    - title: Additional Configuration
      properties:
        environmentVariables:
          title: Environment Variables
          type: object
          description: Additional environment variables for MCP configuration
          ui:widget: object
          additionalProperties:
            type: string
          ui:help: 'Key-value pairs for environment configuration'

  steps:
    - id: fetch-mcp-source
      name: Fetch MCP Server Source Code
      action: fetch:plain
      input:
        url: https://github.com/bayer-int/mcp-servers/tree/main/src/${{ parameters.mcpType }}
        targetPath: ./output/${{ parameters.targetPath }}
            
    - id: create-pr
      name: Create Pull Request with MCP Integration
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: 'feat/add-mcp-${{ parameters.mcpType }}'
        title: 'feat: Add ${{ parameters.mcpType }} MCP server'
        description: |
          ## Add MCP Server: ${{ parameters.serviceName }}
          
          This PR adds the production-ready **${{ parameters.mcpType }}** MCP server from [bayer-int/mcp-servers](https://github.com/bayer-int/mcp-servers).
          
          **Details:**
          - **Server Type**: ${{ parameters.mcpType }} MCP Server
          - **Service Name**: ${{ parameters.serviceName }}
          - **Owner**: ${{ parameters.owner }}
          {% if parameters.databaseUrl %}- **Database**: ${{ parameters.databaseUrl }}{% endif %}
          
          **What Was Added:**
          - `${{ parameters.targetPath }}/` - Complete MCP server implementation
          - Production-ready FastMCP server
          - AWS Lambda deployment ready
          
          **Next Steps:**
          1. Configure environment variables as needed
          2. Start server: `cd ${{ parameters.targetPath }} && uv run main.py`
          3. Deploy to AWS using included Terraform configuration
          
          Generated using Backstage template.
          
          **Documentation:** [bayer-int/mcp-servers](https://github.com/bayer-int/mcp-servers)
        targetPath: ${{ parameters.targetPath }}
        sourcePath: ./output
        token: ${{ secrets.USER_OAUTH_TOKEN }}

  output:
    links:
      - title: Repository
        url: ${{ steps['create-pr'].output.remoteUrl }}
      - title: Pull Request
        url: ${{ steps['create-pr'].output.pullRequestUrl }}
      - title: MCP Documentation
        url: https://modelcontextprotocol.io/
      - title: Setup Instructions
        url: ${{ steps['create-pr'].output.remoteUrl }}/blob/${{ steps['create-pr'].output.targetBranchName }}/${{ parameters.targetPath }}
